### PR TITLE
Typo in persistenceAdapter.loadDatabase

### PR DESCRIPTION
**Pull request by Johnsel**
Hello everyone, I found a typo. :)

51 specs, 0 failures
Finished in 0.161 seconds

### CODE REVIEW

**Comment by ArekSredzki** [comment]
+1
@techfort any chance we could get this merged in today? :)

**Comment by techfort** [comment]
@ArekSredzki @Johnsel that's done! v1.3.15

**Comment by ArekSredzki** [comment]
@techfort Thanks!

**Comment by obeliskos** [comment]
Yes thanks everyone

**Pull request merged**
