### PR TITLE
Add option to disable meta property for documents added to a collection

### PR DESCRIPTION
**Pull request by thomasconner**

### CODE REVIEW

**Comment by thomasconner** [comment]
Fix #368

**Comment by obeliskos** [comment]
Looks good, since some features of LokiJS depend on meta function, can you some consistency checks to the Collection constructor?  The collection features / options which depend on meta are :
- ChangesAPI (enabled when collection constructor option 'disableChangesApi' is passed 'false')
- DeltaChangesAPI (enabled when collection constructor option 'disableDeltaChangesApi' is passed 'false')
- TTL (enabled when collection constructor options 'ttl' and 'ttlInterval' are passed values > 0) 

I would suggest adding a check in collection constructor that if any of the above features are enabled that we do not allow disableMeta functionality to be enabled (true).   We could either throw error if that happens or have those options override the 'disableMeta' option (disableMeta will be forced to be false if either of the others are false (enabled)).  

Thanks! Let me know if you have any concerns or suggestions with the above.

**Comment by obeliskos** [comment]
I will look into adding those consistency checks later today (along with merge of existing pr) if you are not in the middle of adding them yourself.

**Comment by thomasconner** [comment]
Thanks @obeliskos for adding those checks and merging the PR.

**Comment by obeliskos** [comment]
No problem, thanks for the pr, that has been asked before by several people.

@Viatorus : I see you approve as well, if any LokiJS2 specific functionality additionally builds on meta we will need to update consistency checks accordingly. 

I am also considering npm-shrinkwrap soon on this repository to protect against library updates affecting loki build toolchain... anyone have thoughts or concerns with that?

**Comment by Viatorus** [comment]
Thank you both for this nice feature. :)
I will port it to LokiJS2 asap.

@obeliskos I think, adding npm-package.lock will do it for us. No need for shrinkwark. Take a look here: https://docs.npmjs.com/files/package-locks

**Comment by thomasconner** [comment]
@obeliskos @Viatorus When do you think this will be released?

**Comment by obeliskos** [comment]
I will probably ask @techfort in a day or two.  I need to look over an issue and update changelog before then.  May take him a few days or so to push to npm... maybe weekend/early next week for a 1.5.2 release?

**Comment by thomasconner** [comment]
Ok sounds great. Thanks!

**Comment by obeliskos** [comment]
@techfort has published 1.5.2 to npm

**Pull request merged**
