### PR TITLE
fix global imports collision workaround #101

### PR DESCRIPTION
**Pull request by hthetiot**

### CODE REVIEW

**Comment by techfort** [comment]
Hey Harold,

i'm going to have to rollback a few changes you made. I like the idea of loki being transferred to a window.thirdparty object, however that's going to break the apps of all those who are instantiating a loki db by just calling `new loki` as they would now have to call `new thidParty.loki`. I'd rather add more detectors so loki gets moved to thirdParty in case angular or some other framework is used. Does that sound ok to you?

**Comment by techfort** [comment]
Btw, i left loki as a property of thirdparty, then that way if the user wants to manually delete window.loki and keep it only in thirdParty they can.

**Comment by hthetiot** [comment]
Leaving window.loki works for me.
I was actually wondering why it was deleted into the angular adapter originally.
Thanks for the update.

**Comment by hthetiot** [comment]
If you want me to re push with keeping window.loki just ask.

**Comment by techfort** [comment]
No problem and thanks for helping out on this!

**Pull request merged**
