### PR TITLE
Fix _getChunk when chunk is empty but next one is not

### PR DESCRIPTION
**Pull request by radex**
Found an ugly (and stupid on my part) bug in production. Thankfully my sanity checks caught it, making diagnosis easier and avoiding data inconsistency :)

### CODE REVIEW

**Comment by radex** [comment]
Funny enough, my initial commit introduced a much more serious bug… and then during the attempt to write a regression test, I found another bug, and fixed that one too ;)

**Comment by gabzim** [comment]
is this going to get merged at some point?

**Comment by radex** [comment]
yes, please merge! This fixes an important bug in IncrementalIndexedDB adapter

**Comment by radex** [comment]
bad bot

**Comment by radex** [comment]
please stop, bot

**Pull request merged**
