### PR TITLE
Let me count by query

### PR DESCRIPTION
**Pull request by dropfen**
Could be useful :)

### CODE REVIEW

**Comment by techfort** [comment]
hey @dropfen , linting failed, i assume on the `if` statement (always use curly brackets). Can you amend and see if the build succeeds? The PR is useful so once checks pass I'll merge right away. Thanks!

**Comment by dropfen** [comment]
hmm..

**Comment by dropfen** [comment]
This is strange:

> lokijs@1.3.10 lint /home/travis/build/techfort/LokiJS
> jshint src/**.js
src/loki-angular.js: line 270, col 25, 'found' used out of scope.
src/loki-angular.js: line 273, col 29, 'found' used out of scope.
src/loki-angular.js: line 274, col 41, 'found' used out of scope.
src/loki-angular.js: line 276, col 29, 'found' used out of scope.
src/loki-angular.js: line 284, col 25, 'found' used out of scope.
src/loki-angular.js: line 285, col 25, 'found' used out of scope.
src/loki-angular.js: line 286, col 38, 'found' used out of scope.
7 errors

looks like loki-angular.js is the bad-guy :)

**Comment by obeliskos** [comment]
Weird... 

I fixed the jshint error in his code and your p.r. looks clean now.

Thanks!

**Pull request merged**
