### PR TITLE
Pull request with test for issue #187 (the issue itself is fixed by #191)

### PR DESCRIPTION
**Pull request by tnarik**
#187

### CODE REVIEW

**Comment by techfort** [comment]
@tnarik thanks for the PR! unfortunately it's failing the build because of a failed test in unique.spec.js. Could you check and revise?

**Comment by techfort** [comment]
@tnarik sorry - it looks like your PR is more of a demonstration of the error than a fix. Will work on this asap as it seems to be a major bug.

**Comment by tnarik** [comment]
Hi. I might not have been clear. 
The PR if adding the use case that fails so that it is reproducible, not the fix.
I am not sure if the intention for 'unique' indices is to prevent the insertion as well or not (I think so, but maybe is not), and nodejs is not my strength, but I'll try to take a look at it and provide a fix as well as the updated spec.

**Comment by tlkiong** [comment]
Thank you. I was experiencing this as well.

**Pull request closed without merging**
