### PR TITLE
RFC: Make the tests run in a browser

### PR DESCRIPTION
**Pull request by roryf**
The changes here are a total hack to just get something working, I'm looking for feedback on whether this is worthwhile and what the best approach might be if so.

Following on from #107, I'm also looking at loki from a browser perspective and want to ensure it's browser support and performance is adequate. I've hacked the existing unit tests to run with Jasmine and Karma, excluding those that don't make sense in a browser context. Barring the `Collection.mode` test these all pass in:

* Chrome 41.0.22772 (OS X)
* Firefox 34 (OS X)
* Safari 8.0.3 (OS X)
* IE 11 (Win8.1)
* IE 9 (Win7)
* Firefox 35 (Win8.1)

I also hacked the `benchmark.js` to run in a browser (via `benchmark.html`) and got the following results in Chrome 41 on a MacBook Air:

```
load (insert) : 44.21ms (113096.58) ops/s
coll.get() : 816.39ms (2449809.53) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 672.89ms (29722.54 ops/s) 20000 iterations
resultset chained find() :  632.06ms (31642.57 ops/s) 20000 iterations
loki dynamic view first find : 644.69ms (31022.66 ops/s) 20000 iterations
loki dynamic view subsequent finds : 4.98ms (4016064.26 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 532.87ms (750652.13 ops/s) 400000 iterations
resultset chained find() :  419.66ms (714864.41 ops/s) 300000 iterations
loki dynamic view first find : 515.01ms (582512.96 ops/s) 300000 iterations
loki dynamic view subsequent finds : 64.02ms (4686035.61 ops/s) 300000 iterations
```

So, assuming this is worthwhile, any comments at this stage? I was looking at how PouchDB manage their tests and there is a wide range of different test suites for different environments. So clearly running the same tests on browser and node isn't the goal, but getting something working should be (IMO).

### CODE REVIEW

**Comment by techfort** [comment]
Hey Rory,

this looks great however the travis build failed, see [this](https://s3.amazonaws.com/archive.travis-ci.org/jobs/55938398/log.txt). Could you take a look and let me know? I have been considering moving over to karma so this is great timing.

**Comment by roryf** [comment]
Fixed now. Like I said, this is a total hack just to prove that it would actually work.

**Comment by techfort** [comment]
Great, thanks a lot! I'm hoping to get browser badges on the back of this process!

**Comment by roryf** [comment]
@techfort erm, okay. Did I mention this was a total hack?

**Comment by techfort** [comment]
yeah you did, but you also kickstarted the browser-compatibility testing process which i was feeling terribly lazy about, now I can just pick up from here. I wrote [gordian](https://github.com/techfort/gordian) as a spartan way to test Loki - but now that Loki has grown so much I'm going to have to ditch gordian in favour of more accepted practices (karma, mocha,jasmine, whatever..). I'll start hacking those tests myself (e.g. replace suite.assertEqual with expect()-type statements) and see if stuff still works. That's what I really meant with the above comment.

**Pull request merged**
