### PR TITLE
Fixes unique index update with new object

### PR DESCRIPTION
**Pull request by ArekSredzki**
Fixes: #422

### CODE REVIEW

**Comment by ArekSredzki** [comment]
@obeliskos This has caused us many production problems, please review, merge, and release a hot-fix as soon as you can :)

**Comment by techfort** [comment]
@ArekSredzki @obeliskos merged and published on both npm and bower. Thanks!

**Comment by obeliskos** [comment]
Oh, wow thanks @ArekSredzki... I apologize if my b397e89a98e418153a2a2436752b1d16cd584936 commit was responsible for any or all of that.

This probably needs a unit test to ensure this functionality continues to function correctly in the future.  If you would like to add unit test to ensure your fixes stay applied feel free to submit.  If you are otherwise sleep deprived from dealing with this I apologize :) in which case I will look into reverse engineering a unit test based on #422.

Thanks!

**Comment by callmeyesh** [comment]
Hey @techfort @ArekSredzki I am referencing 1.3.17 in my package.json and npm is downloading the right version. This fix is not present in the downloaded version.

**Comment by techfort** [comment]
@callmeyesh @ArekSredzki @obeliskos my bad, i was working on a different branch so v1.3.17 actually did not contain the fix. I deleted 1.3.17 and published a 1.3.18. Apologies

**Comment by callmeyesh** [comment]
@techfort Awesome thank you.

**Pull request merged**
