### PR TITLE
Return event listener index

### PR DESCRIPTION
**Pull request by cristyansv**
now return a array on event listener index.

### CODE REVIEW

**Comment by techfort** [comment]
@cristyansv  this looks good, but can I ask why the index is wrapped into an array when returned?

**Comment by cristyansv** [comment]
@techfort I thought doing so for consistency

```javascript
coll.on(['insert', 'update', 'delete'], callback);

// return int[], returns each index of each event

coll.on('insert', callback);

// return int[], return the index of an event.
```

I thought it would be more reasonable to always return the same data type.

**Comment by techfort** [comment]
hey @cristyansv i have to think more about this. It definitely represents a breaking change for anybody who's expecting an integer and gets an array.
Upon review I might add this to the 2.0 branch.

**Comment by cristyansv** [comment]
hi @techfort 

> It definitely represents a breaking change for anybody who's expecting an integer and gets an array.

this is the code prior to my first commit
```javascript
LokiEventEmitter.prototype.on = function (eventName, listener) {
      var event,
          self;

      if (Array.isArray(eventName)) {
        eventName.forEach(function(currentEventName) {
          self.on(currentEventName, listen);
        });
      }

      event = this.events[eventName];
      if (!event) {
        event = this.events[eventName] = [];
      }
      event.push(listener);
      return listener;
    };
```
Currently it returns a **callback**, not an integer or the index of the event.

**Comment by techfort** [comment]
@cristyansv ok i got confused there. If you want to amend the PR to return the callback so it doesn't represent a breaking change i'll be happy to merge.

**Pull request closed without merging**
