### PR TITLE
Automatic document updates via Object.observe

### PR DESCRIPTION
**Pull request by Cortys**
As discussed in #231.

Because Object.observe is async, updates that cause a unique key violation fail without throwing and only emit an error event, that cannot be safely associated to the invalid object.

I'm not sure about how much of an issue this is and if it has to be resolved before merging.

### CODE REVIEW

**Comment by obeliskos** [comment]
Looks good so far.  Code looks clean, tests pass, and benchmarks are at par with previous (at least without it enabled in our benchmark).  It will take time to look over and i'll let @techfort have plenty of time to review, but looks fine to me.  Maybe a wiki page or paragraph to explain this once it is in main branch?

**Comment by obeliskos** [comment]
Code looks great, I assume @techfort is busy on other tasks so i'll just go ahead and merge this.

If you feel inclined to do so, could you write up a description of how to use this for wiki?

Thanks!

**Comment by Cortys** [comment]
Sure, I'll try to get it done by the end of this week.

Do you plan to release this in 1.3.11 or 1.4?

**Comment by obeliskos** [comment]
@Techfort does all the releases and versioning so maybe he can give you an idea on this... whenever he gets back.  He may need congratulations and a cigar as well ;)

**Comment by obeliskos** [comment]
I do very much appreciate the unit tests by the way... that helps out a lot.

**Pull request merged**
