### PR TITLE
No need to convert array to json before using loki doc update

### PR DESCRIPTION
**Pull request by helzgate**
..also i had 2 underscores in a function call.

### CODE REVIEW

**Comment by obeliskos** [comment]
Thanks again.  Hope to mess around with this sometime soon.

If you feel like making a wiki page to documenting this or just adding comment header, that would be great as well.

**Comment by helzgate** [comment]
Where do i create the wiki page?

**Comment by obeliskos** [comment]
Just go here : 
https://github.com/techfort/LokiJS/wiki

Click new page, name it, and enter and revise at will.  Once I see it out there I will integrate it into our sidebar.

**Comment by obeliskos** [comment]
Looks good, I linked it to wiki sidebar.  Feel free to revise if you ever need to... also might be good to remove badges.

Thanks!

**Pull request merged**
