### PR TITLE
Change ResultSet instantiator from multiple args to a collection arg + opts arg

### PR DESCRIPTION
**Pull request by alexandernst**
WIP #346

### CODE REVIEW

**Comment by alexandernst** [comment]
@techfort @VladimirTechMan @obeliskos Are we good with this? Can we merge it or does it need changes?

**Comment by techfort** [comment]
@VladimirTechMan @obeliskos @alexandernst it looks good but i am really twitchy about this. Tests pass and all, but can you please give it a last review.

**Comment by obeliskos** [comment]
I skimmed it  and intended to look at it more thoroughly, but its been hard to find time.  I probably wont have time to look in detail until the weekend.  From just a cursory glance looks good.

**Comment by alexandernst** [comment]
@obeliskos Have you had time to check on this? What do you think?

**Comment by obeliskos** [comment]
Once again all queries will be affected by this so it is critical path and must be taken more slowly to assess.  Initial benchmarks so this is a hit to indexed search performance so I may need to examine it more.  Can you run benchmarks before and after to verify?  There will always be some fluctuation in results but the range seems lower.  

I do not have as much time to devote to lokijs right now so if anyone else has concerns or wants to diagnose this, feel free.  Otherwise I might need a day or two to get around finding performance hit.

**Comment by alexandernst** [comment]
Yes, of course, I can run benchmarks. I'll post back the results here, but I suspect there will some small performance degradation.

**Comment by alexandernst** [comment]
Those are the results <b>with</b> this patch:

```
load (insert) : 38.85ms (128700.13) ops/s
coll.get() : 2615.41ms (764698.46) ops/s
coll.by() : 2662.49ms (751176.53) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 769.09ms (26004.76 ops/s) 20000 iterations
resultset chained find() :  771.72ms (25916.14 ops/s) 20000 iterations
loki dynamic view first find : 881.79ms (22681.14 ops/s) 20000 iterations
loki dynamic view subsequent finds : 40.77ms (490556.78 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 1237.61ms (323203.59 ops/s) 400000 iterations
resultset chained find() :  986.35ms (304151.67 ops/s) 300000 iterations
loki dynamic view first find : 2693.15ms (111393.72 ops/s) 300000 iterations
loki dynamic view subsequent finds : 563.49ms (532396.32 ops/s) 300000 iterations
```

Those are the results <b>without</b> this patch:

```
load (insert) : 39.09ms (127909.95) ops/s
coll.get() : 2576.72ms (776180.57) ops/s
coll.by() : 2587.17ms (773045.45) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 772.14ms (25902.04 ops/s) 20000 iterations
resultset chained find() :  702.84ms (28455.98 ops/s) 20000 iterations
loki dynamic view first find : 822.96ms (24302.52 ops/s) 20000 iterations
loki dynamic view subsequent finds : 32.61ms (613308.80 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 1072.51ms (372956.90 ops/s) 400000 iterations
resultset chained find() :  821.77ms (365065.65 ops/s) 300000 iterations
loki dynamic view first find : 2472.96ms (121312.11 ops/s) 300000 iterations
loki dynamic view subsequent finds : 458.01ms (655007.53 ops/s) 300000 iterations
```

There are some small fluctuations in the results, some tests are faster with this patch, some tests are slower, but I'd say there are no significant differences.

**Comment by VladimirTechMan** [comment]
@alexandernst @techfort @obeliskos Hey, guys. I was not active on this discussion (ah, I should've) as I happened to be completely tied up over the last week, relocating to the USA for my contractual work. The next few weeks will be busy too – and all the free time that I can get now will likely be spent on my project (built with Loki) as I want to release it ASAP. Having said that, this topic and a few others that directly affect Loki's performance will get my attention: Being one of the most (if not the most) performance-sensitive usages of Loki at the moment, where I use it on doc sets of up to 40-50K docs in a collection, all in browser, I will have to ensure that I am not negatively affected by any changes. After all, a bunch of previous patches from me was all focused on optimizing Loki to the level that allowed me to use on 40-50K doc collections. Thus, I certainly don't want to degrade performance that I was able to achieve with all the improvements done over Jan-Feb timeframe. :)

I intend to make tests with the changes done by @alexandernst today or in a few days, and will report my results. (The results reported by @alexandernst look good so far. Fingers crossed.)

Now, l have one personal "dislike" though about the changes done. When using the optional arguments for JavaScript functions or "constructors", I tend to prefer the style where the mandatory arguments (= those that must be always supplied) remain direct dedicated arguments of the function. And the truly optional arguments go into the `options` argument, which "sits" as the final argument of the function. From that perspective: `ResultSet` cannot go without the associated `collection`. But it can go without the other parameters (query, where-function, `firstOnly`, etc.) With that in mind, I would recommend to @alexandernst to slightly modify the proposed patch, so that `collection` remains the first "explict" argument of `ResultSet` and `options` goes as the second one (and it can be omitted completely when there is no any optional arguments needed). That would help both with the code clarity and it would (slightly) reduce the complexity of handling the args inside the function, while preserving all the benefits of the approach with the options-argument. I hope that makes sense to you too, but let me know if you have any concerns about it from your perspective.

**Comment by alexandernst** [comment]
@VladimirTechMan Sure, that makes sense, in fact I think I already saw a couple of functions in Loki that use that exact same methodology (1 unconditional arg + 1 object-arg).

About the performance, keep in mind that this patch touches a code path that isn't performance-sensitive (unless you're removing and creating 40k collections per seconds, which I doubt).

This change affects the code path used to create a new resultset, so it's basically called once per `.find()` (and family).

If you want to speed things up, pay attention at my talk with @obeliskos in https://github.com/techfort/LokiJS/pull/358 . *THAT* (memoization) will help you speed your 50k docs queries.

**Comment by alexandernst** [comment]
Ok, I did the changed required by @VladimirTechMan 

New benchmark results with the latest patch:

```
load (insert) : 42.01ms (119019.28) ops/s
coll.get() : 2675.73ms (747459.57) ops/s
coll.by() : 2667.64ms (749726.35) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 753.27ms (26550.90 ops/s) 20000 iterations
resultset chained find() :  756.08ms (26452.23 ops/s) 20000 iterations
loki dynamic view first find : 868.90ms (23017.61 ops/s) 20000 iterations
loki dynamic view subsequent finds : 42.34ms (472366.56 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 1381.45ms (289550.83 ops/s) 400000 iterations
resultset chained find() :  941.42ms (318667.54 ops/s) 300000 iterations
loki dynamic view first find : 2672.10ms (112271.25 ops/s) 300000 iterations
loki dynamic view subsequent finds : 544.61ms (550852.90 ops/s) 300000 iterations
```

**Comment by VladimirTechMan** [comment]
@alexandernst Yeah, I know (and fully agree) in this case it is not on the critical path (at least, not for my use cases). My comment on perf above was a more generic one – essentially, a reply to you and @techfort and @obeliskos over the bunch of suggested code changes and discussions on-going in the last days. Sorry for confusion.

As for the memorization, yes, I certainly saw that. It can make good sense – and I considered it myself as one potential way to improve things about a month ago. But I did not get to playing with it myself (instead, I've found a bunch of other places in the code that allowed to improve performance notably for my app, during that period of time). So, it is very good that there is someone thinking in the same direction and willing to dig into that. The devil is in details, of course, as usual. I will want to look closer at your proposal on the actual code changes – and then try in my project and see how well they help in my case. Depending on my load, maybe I will be able to help you with that implementation too, but not sticking my neck on that too far at the moment, to be on the safe side. :)

**Comment by VladimirTechMan** [comment]
@techfort @obeliskos Looks good to me.

@alexandernst My only other small comment here: Could you correct the jsdoc markup in the preceding comment, to match the changed function params?

**Comment by alexandernst** [comment]
Done :)

**Comment by obeliskos** [comment]
That still looks like a significant performance hit to collection.find() for a refactor that is only internal to loki.  I have not had time to look into why there is any slowdown at all, but I can't think of a reason why there should be any performance hit associated with this.

**Comment by alexandernst** [comment]
@obeliskos Those are just fluctuations in the benchmark results. Anyways, I insist on the very important thing here, that is, this codepath is not performance critical. The +/-3% speed difference in there isn't added per-queried-document, but per-query itself. Meaning, if a query on 5000 objects takes 100ms without this patch, with this patch it will take 103ms, and not 100ms + (3ms * 5000).

The patch is affecting the `ResultSet` class, which is instantiated only once per query.

**Comment by obeliskos** [comment]
Well your indexed resultset.find() results went from 372956.90 ops/s to 289550.83 ops/s which is more like a 25% hit.  I had encountered similar performance hit back when I originally voiced concern.  As you mentioned this 'should' not affect performance since cost should be paid once per query and we should be essentially just wrapping parameters.... but it seemed as if it was somewhere else.

**Comment by alexandernst** [comment]
I noticed that even running the same benchmark twice, without any code modifications, the output might be slightly different. It's hard to guess from where exactly this is coming (the code base is huge), but this change just can't render such a big performance regression, just because the one and only thing that is doing is change the number of arguments (and converts them from multiple primitives to one object).

Then again, I just ran the benchmarks again:

```
# alexandernst at stupidbox in ~/tmp_loki/node_modules/lokijs/benchmark on git:master o [23:52:54]
$ node benchmark
load (insert) : 33.30ms (150150.15) ops/s
coll.get() : 2626.75ms (761397.16) ops/s
coll.by() : 2664.66ms (750564.80) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 756.32ms (26443.83 ops/s) 20000 iterations
resultset chained find() :  769.34ms (25996.31 ops/s) 20000 iterations
loki dynamic view first find : 922.32ms (21684.45 ops/s) 20000 iterations
loki dynamic view subsequent finds : 27.77ms (720201.66 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 1397.80ms (286163.97 ops/s) 400000 iterations
resultset chained find() :  950.46ms (315636.64 ops/s) 300000 iterations
loki dynamic view first find : 2670.60ms (112334.31 ops/s) 300000 iterations
loki dynamic view subsequent finds : 566.01ms (530025.97 ops/s) 300000 iterations

# alexandernst at stupidbox in ~/tmp_loki/node_modules/lokijs/benchmark on git:master o [23:53:20]
$ node benchmark
load (insert) : 37.73ms (132520.54) ops/s
coll.get() : 2654.83ms (753343.91) ops/s
coll.by() : 2690.55ms (743342.44) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 792.74ms (25228.95 ops/s) 20000 iterations
resultset chained find() :  765.19ms (26137.30 ops/s) 20000 iterations
loki dynamic view first find : 893.30ms (22388.90 ops/s) 20000 iterations
loki dynamic view subsequent finds : 30.63ms (652954.62 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 1460.45ms (273888.19 ops/s) 400000 iterations
resultset chained find() :  969.16ms (309546.41 ops/s) 300000 iterations
loki dynamic view first find : 2688.65ms (111580.16 ops/s) 300000 iterations
loki dynamic view subsequent finds : 601.64ms (498637.06 ops/s) 300000 iterations

# alexandernst at stupidbox in ~/tmp_loki/node_modules/lokijs/benchmark on git:master o [23:53:49]
$ node benchmark
load (insert) : 41.35ms (120918.98) ops/s
coll.get() : 2619.52ms (763498.66) ops/s
coll.by() : 2614.59ms (764938.29) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 769.01ms (26007.46 ops/s) 20000 iterations
resultset chained find() :  760.70ms (26291.57 ops/s) 20000 iterations
loki dynamic view first find : 878.92ms (22755.20 ops/s) 20000 iterations
loki dynamic view subsequent finds : 42.50ms (470588.24 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 1448.72ms (276105.80 ops/s) 400000 iterations
resultset chained find() :  945.46ms (317305.86 ops/s) 300000 iterations
loki dynamic view first find : 2708.01ms (110782.46 ops/s) 300000 iterations
loki dynamic view subsequent finds : 513.88ms (583793.88 ops/s) 300000 iterations

# alexandernst at stupidbox in ~/tmp_loki/node_modules/lokijs/benchmark on git:master o [23:54:37]
$ node benchmark
load (insert) : 42.25ms (118343.20) ops/s
coll.get() : 2551.08ms (783981.69) ops/s
coll.by() : 2625.05ms (761890.25) ops/s

-- Benchmarking query on NON-INDEXED column --
coll.find() : 753.95ms (26526.96 ops/s) 20000 iterations
resultset chained find() :  756.78ms (26427.76 ops/s) 20000 iterations
loki dynamic view first find : 879.30ms (22745.37 ops/s) 20000 iterations
loki dynamic view subsequent finds : 27.28ms (733137.83 ops/s) 20000 iterations

-- ADDING BINARY INDEX to query column and repeating benchmarks --
coll.find() : 1430.29ms (279663.56 ops/s) 400000 iterations
resultset chained find() :  962.41ms (311717.46 ops/s) 300000 iterations
loki dynamic view first find : 2545.97ms (117833.28 ops/s) 300000 iterations
loki dynamic view subsequent finds : 594.57ms (504566.33 ops/s) 300000 iterations
```

Now tests are hitting the 1400ms mark, and the code hasn't been changed. It's either some faulty benchmark assumption (I have plenty of those in my projects) or some other part of the code is acting funny.

**Comment by obeliskos** [comment]
Ok this is weird, I altered your parameter copying routine to the following (in Resultset constructor) : 
```javascript
options = options || {};

options.collection = options.collection || [];
options.queryObj = options.queryObj || null;
options.queryFunc = options.queryFunc || null;
options.firstOnly = options.firstOnly || false;
```

Do me a favor and run benchmarks of existing pr and just write down the 'indexed collection find' result.  Run twice or three times.  Then update the default param copying logic to something like above (get rid of the for-in loop) and then run bench twice and write down result.

For me after making mods above it ran faster with the pr than without... but as I said I would like to corroborate benchmarks.

**Comment by alexandernst** [comment]
Let's see. master + this PR:

    coll.find() : 1193.04ms (335277.95 ops/s) 400000 iterations
    coll.find() : 1213.35ms (329665.80 ops/s) 400000 iterations
    coll.find() : 1382.87ms (289253.51 ops/s) 400000 iterations

master + this PR + your proposed changes:

    coll.find() : 1060.92ms (377031.26 ops/s) 400000 iterations
    coll.find() : 1247.08ms (320749.27 ops/s) 400000 iterations
    coll.find() : 1076.37ms (371619.42 ops/s) 400000 iterations

While the second set of results "looks" better, keep in mind that there are some fluctuations in the code. Look at how the first and the second test went from `1060.92` to `1247.08`, and then back to `1076.37`.

If I had to guess, I'd say those benchmarks are doing some wrong assumptions.

Anyways, do you want me to update this PR with that code change?

**Comment by obeliskos** [comment]
Yes please... on my box I originally was in the 700k range, the pr lowered to around the 550-600 range, and after changes I am around 750-850 range and it seems repeatable (although with fluctuations).

Yes, what those numbers indicate is our ability to 'instantiate a resultset and run a query' 700,000 times a second.  Whether or not that is 'real world' demands it represents minute milliseconds off each query.  Our benchmarks are doing single simple $eq op so... as it relates to this pr... mainly just to asses overhead.  

As I mentioned before, the rest of the pr seemed to speed up this pipeline so I am great if you make those changes.

**Comment by alexandernst** [comment]
Done :+1:

**Comment by obeliskos** [comment]
Hmm travis ci is slow, i will wait.  Thanks for working with @VladimirTechMan too... I think he said he is good with this so once travis posts success I will go ahead and merge.

Thanks!

**Comment by alexandernst** [comment]
No problem, thank you for checking on this!

**Comment by obeliskos** [comment]
Not tonight.. there have been so many issues posted recently I will need a day or so to catch up.  I think I saw you post that you finished looking at Lt/gt combinations. I'll try to look that over soon so let's continue in that issue.

**Pull request merged**
