### PR TITLE
Allow sorting on nested properties; closes #574

### LINKED ISSUE #574: sorting on sub properties of and object
i'm trying to sort an array on a sub property of an object without success. For example..
```
items.insert({ name : 'mjolnir', owner: { test: 'a'});
items.insert({ name : 'gungnir', owner: { test: 'b'});
items.insert({ name : 'tyrfing', owner: {test: 'c'});

logObject(items.chain().find({'name': {'$contains': 'i'}}).compoundsort([['owner.test', false]]).data() );
logObject(items.chain().find({'name': {'$contains': 'i'}}).compoundsort([['owner.test', true]]).data() );
```
the 2 logs give the same response even though one of them should be reversed.

### PR DESCRIPTION
**Pull request by Redsandro**
Introducing a fix for #574; allowing to sort on nested properties by specifying them as a dotted string like so:

```
my.nested.key
```

### CODE REVIEW

**Comment by Redsandro** [comment]
I'm sorry about the removal of spaces in the diff. My editor automatically removes trailing space, as it is defined in your `.editorconfig`.

**Comment by obeliskos** [comment]
Sweet, thanks!

**Comment by Redsandro** [comment]
@obeliskos could you publish this on `npm`?

**Comment by obeliskos** [comment]
I will try to round up any outstanding issues and then we can request that @techfort publish a 1.5.1 version.

**Comment by obeliskos** [comment]
I think we are good for another release now...

@techfort can you do a publish of 1.51 to npm?

**Pull request merged**
