### PR TITLE
change 'shallow-recurse-objects' clone to support deep Array clone

### PR DESCRIPTION
**Pull request by jonathanz**
fix transform not support $or and $and issue, for $or and $and whose top children are Array, current transform use 'shallow-recurse-objects', which not deep clone Array, change 'shallow-recurse-objects' clone to support deep Array clone.
Example transform:
    var memberleveltx = [
        {
            type: 'find',
            value: {
                '$or': [
                    {
                        'crowd.anyone': true
                    },
                    {
                        'crowd.specified.grade.value': {$contains: '[%lktxp]grade'}
                    }
                ]
            }
        }
    ];

### CODE REVIEW

**Comment by obeliskos** [comment]
Hey @jonathanz can you provide a unit test in spec/generic/transforms.spec.js to cover the use case which this fixes?

**Comment by jonathanz** [comment]
Hey @obeliskos uint test for this fix has been added. please check it.

**Comment by jonathanz** [comment]
Hey @obeliskos uint test for this fix has been added. please check it.

**Comment by obeliskos** [comment]
Looks good, thanks for pointing this out and fixing... that would seem to be a somewhat common use case we overlooked.

**Pull request merged**
